### ISSUE TITLE
Add the next lines in the file with the language

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ServerAuth#38]
To make the description of commands in a file for languages

/sa help

**Comment by Flavius12** [comment]
This feature require a big change of code but I'll keep it in mind

**Comment by Flavius12** [comment]
Done :+1:
But I need the russian translation now :smile:
(Replace only English messages)

``` yml
#ServerAuth plugin Russian language file
#Translation by Pub4Game
---
join-message: "&bНа этом сервере используется авторизация &7- &aServerAuth"
single-auth: "&cИгрок с таким ником уже играет на сервере!"
mysql-success: "&aServerAuth успешно подключен к базе данных MySQL!"
mysql-restored: "&aMySQL соединение восстановлено!"
mysql-fail: "&cServerAuth не может подключиться к базе данных MySQL. Все данные будут сохранены локально. Ошибка: {MYSQL_ERROR}" 
config-reloaded: "&aКонфигурация плагина перезагружена!"
operation-cancelled: "&cДействие отменено"
login:
  message: "&cДля авторизации на сервере /login <пароль>"
  disabled: "&cАвторизация отключена на данном сервере"
  command: "&cИспользуйте: /login <пароль>"
  ip-login: "&9Вы уже вошли на сервер с данного IP"
  login-success: "&aВы успешно вошли в свой аккаунт!"
  login-timeout: "&cВремя ожидания авторизации закончилось"
  already-login: "&aВы уже вошли в свой аккаунт!"
  too-many-attempts: "&cВы делаете слишком много попыток входа!"
register:
  message: "&cПожалуйста, зарегистрируйтесь на сервере /register <пароль>"
  message-conf: "&cПожалуйста, зарегистрируйтесь на сервере /register <пароль> <повтор пароля>"
  disabled: "&cРегистрация отключена на данном сервере"
  command: "&cИспользуйте: /register <пароль>"
  command-conf: "&cИспользуйте: /register <пароль> <повтор пароля>"
  register-success: "&aВы успешно зарегистрировались!"
  register-timeout: "&cВремя ожидания регистрации закончилось"
  already-registered: "&aВы уже зарегистрировали свой аккаунт!"
changepassword:
  disabled: "&cИзменение пароля отключено на данном сервере"
  login-required: "&cПожалуйста, войдите в свой аккаунт, после чего смените пароль!"
  command: "&cИспользуйте: /changepassword <новый пароль>"
  command-conf: "&cИспользуйте: /changepassword <новый пароль> <повтор пароля>"
  command-cons: "&cUsage: /changepassword <player> <newPassword>"
  changepassword-success: "&aПароль был успешно изменен!"
  changepassword-cons-success: "&aPassword for user &b{PLAYER} &achanged to &b{PASSWORD}"
logout:
  disabled: "&cВыход из аккаунта отключен на данном сервере"
  logout-success: "&aВы успешно вышли из своего аккаунта"
unregister:
  disabled: "&cУдаление аккаунта отключено на сервере"
  login-required: "&cПожалуйста, войдите в свой аккаунт, после чего повторите попытку!"
  command: "&cИспользуйте: /unregister <пароль>"
  command-cons: "&cИспользуйте: /unregister <ник>"
  unregister-success: "&aВы успешно удалили свой аккаунт!"
  unregister-success-3rd: "&aВы успешно удалили аккаунт игрока!"
help:
   1: "&b=> &aAvailable Commands &b<="
   2: "&a/changepassword &b=>&a Change the account password"
   3: "&a/login &b=>&a Do login"
   4: "&a/logout &b=>&a Do logout"
   5: "&a/register &b=>&a Register an account"
   6: "&a/serverauth help &b=>&a Show help about this plugin"
   7: "&a/serverauth info &b=>&a Show info about this plugin"
   8: "&a/serverauth reload &b=>&a Reload the config"
   9: "&a/unregister &b=>&a Unregister your account"
   error: "&cSubcommand &a{SUBCMD} &cnot found. Use &a/serverauth help &cto show available commands"
errors:
  generic: "&cПроизошла ошибка"
  wrong-password: "&cВы ввели неверный пароль!"
  password-no-match: "&cПароли не совпадают"
  password-too-short: "&cВаш пароль слишком короткий!"
  password-too-long: "&cВаш пароль слишком длинный!"
  user-not-registered: "&cВы не зарегистрированы!"
  user-not-registered-3rd: "&cИгрок с таким ником не зарегистрирован!"
  user-not-authenticated: "&cВы не авторизовались!"
  max-ip-reached: "&cВы достигли максимальное число регистраций с одного IP"
  no-permissions: "&cYou don't have permissions to use this command"
  player-only: "&cYou can only perform this command as a player"
...
```
